<%-- @Author: Yann POSTEC --%>
<%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:requestEncoding value="UTF-8" />
<fmt:setBundle basename="ypodev.adrezo.props.jslang" />
<%@ taglib prefix="json" uri="http://www.atg.com/taglibs/json" %>
<%request.setCharacterEncoding("UTF-8");%>
<c:if test="${validUser != null && pageContext.request.method == 'POST'}">
<json:object escapeXml="false">
	<json:property name="xhrapperror"><fmt:message key="js.xhrapperror" /></json:property>
	<json:property name="xhrapptext"><fmt:message key="js.xhrapptext" /></json:property>
	<json:property name="error"><fmt:message key="js.error" /></json:property>
	<json:property name="xhrpreload"><fmt:message key="js.xhrpreload" /></json:property>
	<json:property name="closedlg"><fmt:message key="js.closedlg" /></json:property>
	<json:property name="xhrerror"><fmt:message key="js.xhrerror" /></json:property>
	<json:property name="xhrvalid"><fmt:message key="js.xhrvalid" /></json:property>
	<json:property name="confirm"><fmt:message key="js.confirm" /></json:property>
	<json:property name="invalidfield"><fmt:message key="js.invalidfield" /></json:property>
	<json:property name="objdel"><fmt:message key="js.objdel" /></json:property>
	<json:property name="dlgyes"><fmt:message key="js.dlgyes" /></json:property>
	<json:property name="dlgno"><fmt:message key="js.dlgno" /></json:property>
	<json:property name="name"><fmt:message key="js.name" /></json:property>
	<json:property name="site"><fmt:message key="js.site" /></json:property>
	<json:property name="vid"><fmt:message key="js.vid" /></json:property>
	<json:property name="code"><fmt:message key="js.code" /></json:property>
	<json:property name="dest"><fmt:message key="js.dest" /></json:property>
	<json:property name="subject"><fmt:message key="js.subject" /></json:property>
	<json:property name="msg"><fmt:message key="js.msg" /></json:property>
	<json:property name="type"><fmt:message key="js.type" /></json:property>
	<json:property name="order"><fmt:message key="js.order" /></json:property>
	<json:property name="annu"><fmt:message key="js.annu" /></json:property>
	<json:property name="initialctx"><fmt:message key="js.initialctx" /></json:property>
	<json:property name="newctx"><fmt:message key="js.newctx" /></json:property>
	<json:property name="auth"><fmt:message key="js.auth" /></json:property>
	<json:property name="role"><fmt:message key="js.role" /></json:property>
	<json:property name="pwd"><fmt:message key="js.pwd" /></json:property>
	<json:property name="login"><fmt:message key="js.login" /></json:property>
	<json:property name="proto"><fmt:message key="js.proto" /></json:property>
	<json:property name="ip"><fmt:message key="js.ip" /></json:property>
	<json:property name="vlan"><fmt:message key="js.vlan" /></json:property>
	<json:property name="mask"><fmt:message key="js.mask" /></json:property>
	<json:property name="ipgw"><fmt:message key="js.ipgw" /></json:property>
	<json:property name="ipbc"><fmt:message key="js.ipbc" /></json:property>
	<json:property name="ctx"><fmt:message key="js.ctx" /></json:property>
	<json:property name="subnet"><fmt:message key="js.subnet" /></json:property>
	<json:property name="verifnotnull"><fmt:message key="js.verifnotnull" /></json:property>
	<json:property name="verifchoose"><fmt:message key="js.verifchoose" /></json:property>
	<json:property name="verifnumber"><fmt:message key="js.verifnumber" /></json:property>
	<json:property name="verifsize"><fmt:message key="js.verifsize" /></json:property>
	<json:property name="verifnoslash"><fmt:message key="js.verifnoslash" /></json:property>
	<json:property name="verifippart"><fmt:message key="js.verifippart" /></json:property>
	<json:property name="verifip"><fmt:message key="js.verifip" /></json:property>
	<json:property name="verifmask"><fmt:message key="js.verifmask" /></json:property>
	<json:property name="caljan"><fmt:message key="js.caljan" /></json:property>
	<json:property name="calfeb"><fmt:message key="js.calfeb" /></json:property>
	<json:property name="calmar"><fmt:message key="js.calmar" /></json:property>
	<json:property name="calapr"><fmt:message key="js.calapr" /></json:property>
	<json:property name="calmay"><fmt:message key="js.calmay" /></json:property>
	<json:property name="caljun"><fmt:message key="js.caljun" /></json:property>
	<json:property name="caljul"><fmt:message key="js.caljul" /></json:property>
	<json:property name="calaug"><fmt:message key="js.calaug" /></json:property>
	<json:property name="calsep"><fmt:message key="js.calsep" /></json:property>
	<json:property name="caloct"><fmt:message key="js.caloct" /></json:property>
	<json:property name="calnov"><fmt:message key="js.calnov" /></json:property>
	<json:property name="caldec"><fmt:message key="js.caldec" /></json:property>
	<json:property name="pwdmatch"><fmt:message key="js.pwdmatch" /></json:property>
	<json:property name="rolenogrp"><fmt:message key="js.rolenogrp" /></json:property>
	<json:property name="roleerror"><fmt:message key="js.roleerror" /></json:property>
	<json:property name="rolenoanswer"><fmt:message key="js.rolenoanswer" /></json:property>
	<json:property name="rolewait"><fmt:message key="js.rolewait" /></json:property>
	<json:property name="upbegin"><fmt:message key="js.upbegin" /></json:property>
	<json:property name="upload"><fmt:message key="js.upload" /></json:property>
	<json:property name="upend"><fmt:message key="js.upend" /></json:property>
	<json:property name="uperr"><fmt:message key="js.uperr" /></json:property>
	<json:property name="upcancel"><fmt:message key="js.upcancel" /></json:property>
	<json:property name="analyserr"><fmt:message key="js.analyserr" /></json:property>
	<json:property name="analysend"><fmt:message key="js.analysend" /></json:property>
	<json:property name="process"><fmt:message key="js.process" /></json:property>
	<json:property name="processend"><fmt:message key="js.processend" /></json:property>
	<json:property name="edbold"><fmt:message key="js.edbold" /></json:property>
	<json:property name="editalic"><fmt:message key="js.editalic" /></json:property>
	<json:property name="edunderline"><fmt:message key="js.edunderline" /></json:property>
	<json:property name="edstrike"><fmt:message key="js.edstrike" /></json:property>
	<json:property name="edsub"><fmt:message key="js.edsub" /></json:property>
	<json:property name="edsuper"><fmt:message key="js.edsuper" /></json:property>
	<json:property name="edorder"><fmt:message key="js.edorder" /></json:property>
	<json:property name="edunorder"><fmt:message key="js.edunorder" /></json:property>
	<json:property name="edoutdent"><fmt:message key="js.edoutdent" /></json:property>
	<json:property name="edindent"><fmt:message key="js.edindent" /></json:property>
	<json:property name="edlalign"><fmt:message key="js.edlalign" /></json:property>
	<json:property name="edcalign"><fmt:message key="js.edcalign" /></json:property>
	<json:property name="edralign"><fmt:message key="js.edralign" /></json:property>
	<json:property name="edjustify"><fmt:message key="js.edjustify" /></json:property>
	<json:property name="edundo"><fmt:message key="js.edundo" /></json:property>
	<json:property name="edredo"><fmt:message key="js.edredo" /></json:property>
	<json:property name="edimg"><fmt:message key="js.edimg" /></json:property>
	<json:property name="edrule"><fmt:message key="js.edrule" /></json:property>
	<json:property name="edilink"><fmt:message key="js.edilink" /></json:property>
	<json:property name="eddlink"><fmt:message key="js.eddlink" /></json:property>
	<json:property name="edformat"><fmt:message key="js.edformat" /></json:property>
	<json:property name="edprint"><fmt:message key="js.edprint" /></json:property>
	<json:property name="delete"><fmt:message key="js.delete" /></json:property>
	<json:property name="none"><fmt:message key="js.none" /></json:property>
	<json:property name="choosesub"><fmt:message key="js.choosesub" /></json:property>
	<json:property name="ipconfirm"><fmt:message key="js.ipconfirm" /></json:property>
	<json:property name="ipserr"><fmt:message key="js.ipserr" /></json:property>
	<json:property name="ipspar"><fmt:message key="js.ipspar" /></json:property>
	<json:property name="ipsparo"><fmt:message key="js.ipsparo" /></json:property>
	<json:property name="ipsparf"><fmt:message key="js.ipsparf" /></json:property>
	<json:property name="ipsinvalid"><fmt:message key="js.ipsinvalid" /></json:property>
	<json:property name="equal"><fmt:message key="js.equal" /></json:property>
	<json:property name="different"><fmt:message key="js.different" /></json:property>
	<json:property name="contain"><fmt:message key="js.contain" /></json:property>
	<json:property name="begin"><fmt:message key="js.begin" /></json:property>
	<json:property name="end"><fmt:message key="js.end" /></json:property>
	<json:property name="nocontain"><fmt:message key="js.nocontain" /></json:property>
	<json:property name="nobegin"><fmt:message key="js.nobegin" /></json:property>
	<json:property name="noend"><fmt:message key="js.noend" /></json:property>
	<json:property name="isnull"><fmt:message key="js.isnull" /></json:property>
	<json:property name="isnotnull"><fmt:message key="js.isnotnull" /></json:property>
	<json:property name="until"><fmt:message key="js.until" /></json:property>
	<json:property name="mig"><fmt:message key="js.mig" /></json:property>
	<json:property name="temp"><fmt:message key="js.temp" /></json:property>
	<json:property name="the"><fmt:message key="js.the" /></json:property>
	<json:property name="ipfutur"><fmt:message key="js.ipfutur" /></json:property>
	<json:property name="ipremoveok"><fmt:message key="js.ipremoveok" /></json:property>
	<json:property name="line"><fmt:message key="js.line" /></json:property>
	<json:property name="date"><fmt:message key="js.date" /></json:property>
	<json:property name="verifrequired"><fmt:message key="js.verifrequired" /></json:property>
	<json:property name="dateformat"><fmt:message key="js.dateformat" /></json:property>
	<json:property name="send"><fmt:message key="js.send" /></json:property>
	<json:property name="sendto"><fmt:message key="js.sendto" /></json:property>
	<json:property name="ipdreplace"><fmt:message key="js.ipdreplace" /></json:property>
	<json:property name="ipdadd"><fmt:message key="js.ipdadd" /></json:property>
	<json:property name="ipdclear"><fmt:message key="js.ipdclear" /></json:property>
	<json:property name="ipdmoreone"><fmt:message key="js.ipdmoreone" /></json:property>
	<json:property name="ipinvalid"><fmt:message key="js.ipinvalid" /></json:property>
	<json:property name="pagenum"><fmt:message key="js.pagenum" /></json:property>
	<json:property name="iptemp"><fmt:message key="js.iptemp" /></json:property>
	<json:property name="ipmig"><fmt:message key="js.ipmig" /></json:property>
	<json:property name="pages"><fmt:message key="js.pages" /></json:property>
	<json:property name="ipgw"><fmt:message key="js.ipgw" /></json:property>
	<json:property name="stkrecep"><fmt:message key="js.stkrecep" /></json:property>
	<json:property name="processerr"><fmt:message key="js.processerr" /></json:property>
	<json:property name="verifvariation"><fmt:message key="js.verifvariation" /></json:property>
	<json:property name="stklimit"><fmt:message key="js.stklimit" /></json:property>
	<json:property name="idx"><fmt:message key="js.idx" /></json:property>
	<json:property name="cat"><fmt:message key="js.cat" /></json:property>
	<json:property name="threshold"><fmt:message key="js.threshold" /></json:property>
	<json:property name="ongoing"><fmt:message key="js.ongoing" /></json:property>
	<json:property name="verifmin"><fmt:message key="js.verifmin" /></json:property>
	<json:property name="sladefault"><fmt:message key="js.sladefault" /></json:property>
	<json:property name="client"><fmt:message key="js.client" /></json:property>
	<json:property name="room"><fmt:message key="js.room" /></json:property>
	<json:property name="set"><fmt:message key="js.set" /></json:property>
	<json:property name="pos"><fmt:message key="js.pos" /></json:property>
	<json:property name="noquote"><fmt:message key="js.noquote" /></json:property>
	<json:property name="photoupend"><fmt:message key="js.photoupend" /></json:property>
	<json:property name="mod"><fmt:message key="js.mod" /></json:property>
	<json:property name="photoname"><fmt:message key="js.photoname" /></json:property>
	<json:property name="rackname"><fmt:message key="js.rackname" /></json:property>
	<json:property name="recto"><fmt:message key="js.recto" /></json:property>
	<json:property name="verso"><fmt:message key="js.verso" /></json:property>	
	<json:property name="mail"><fmt:message key="js.mail" /></json:property>
	<json:property name="port"><fmt:message key="js.port" /></json:property>
	<json:property name="uri"><fmt:message key="js.uri" /></json:property>
	<json:property name="all"><fmt:message key="js.all" /></json:property>
	<json:property name="verifnet"><fmt:message key="js.verifnet" /></json:property>
	<json:property name="calcnosub"><fmt:message key="js.calcnosub" /></json:property>
	<json:property name="filesize"><fmt:message key="js.filesize" /></json:property>
	<json:property name="sladel"><fmt:message key="js.sladel" /></json:property>
	<json:property name="verifothersubnet"><fmt:message key="js.verifothersubnet" /></json:property>
	<json:property name="stkmove"><fmt:message key="js.stkmove" /></json:property>
	<json:property name="stksrc"><fmt:message key="js.stksrc" /></json:property>
	<json:property name="stkdst"><fmt:message key="js.stkdst" /></json:property>
	<json:property name="stkqty"><fmt:message key="js.stkqty" /></json:property>
	<json:property name="planning"><fmt:message key="js.planning" /></json:property>
	<json:property name="dhcpscopeerror"><fmt:message key="js.dhcpscopeerror" /></json:property>
	<json:property name="dhcpscopeno"><fmt:message key="js.dhcpscopeno" /></json:property>
	<json:property name="dhcpscopewait"><fmt:message key="js.dhcpscopewait" /></json:property>
</json:object>	
</c:if>
